### PR TITLE
Support for loop fields

### PR DESCRIPTION
**Pull request by camiloclc**
Fix for loop fields, they were previously unsupported and made the sync process fail.

PS: sorry for the delay!

### CODE REVIEW

**Comment by mgibbs189** [comment]
Thanks for the pull request. I know it's taken forever, but I'll try to review it shortly.

**Comment by camiloclc** [comment]
No problem, things have been crazy here too. There's a possible problem with this code: it doesn't seem to support nested loops, only first level. I haven't tested it in that situation, the thought occurred to me recently.

**Comment by nicolas-san** [comment]
@camiloclc @mgibbs189 
Hello all :) 
I've to migrate some CFS datas, and I was ready to write some php to do the job, but I see the Synchronizer, and try it, and no luck... After few search I figured I was because of fields in fields, so I see this PR, and think YESSS ! It's perfect.

I try it, and well, it's perfect ! :)

Thank you for the plugin, and the PR, you have one beta tester ok, and if you need some additionnal tests, let me know

**Comment by mgibbs189** [comment]
Sounds good to me. Thanks @camiloclc

**Pull request merged**
